apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: coworking
  region: us-east-1

nodeGroups:
  - name: ng-1
    desiredCapacity: 2
    instanceType: t4.micro

addons:
  - name: vpc-cni
    version: latest
